@startuml ex04_gherkin_outline
skinparam defaultFontName "DejaVu Sans"
skinparam defaultFontSize 14
skinparam backgroundColor #FFFFFF
skinparam shadowing false
skinparam roundcorner 8
skinparam ArrowColor #334155
skinparam titleFontColor #0F172A
skinparam titleFontSize 20
skinparam noteBackgroundColor #FFF7ED
skinparam noteBorderColor #D97706
skinparam dpi 140
title Gherkin: Scenario Outline + Examples (таблица данных вместо дублирования)
note as N1 #LightBlue
Scenario Outline: Применение промокода
  Given активная бронь на сумму <summa>
  When  я применяю промокод <code>
  Then  к списанию равен <itog>

  Examples:
  | summa | code   | itog |
  | 1000  | SALE10 | 900  |
  | 1000  | EXPIRED| ошибка |
  | 1000  |        | 1000 |
end note
rectangle "Каждая строка Examples = отдельный автотест\n(параметризованный сценарий)" as N2
N1 -down-> N2
@enduml
